### ISSUE TITLE
2900 items to be synced to Github

### ISSUE THREAD

**Issue by vinostroud** [vinostroud/PDI_Bytes#10]
First, let me apologize for bombarding you with questions, but I've gotten stuck in multiple spots and don't want to let a mess fester in my vscode.

When I open my virtual environment, I see 2943 items to be synced to my Github. (Screen shot below)

Edit : I dont think the below paragraph is correct, as I looked at the files to be synced and they all appear to be in my `PDI Bytes` folder and they appear to be scripts and packages related to python. Do I sync everything so that the final packages work?

What I'm seeing is attached as a screen shot:

(And apologies as I know this is a VSCode question vice a python question)

![Screenshot 2023-08-10 091831](https://github.com/vinostroud/PDI_Bytes/assets/134710724/cdf1f876-10d9-434a-ba75-30e855799d96)

Text that is now irrelevant:
_Part of the issue may be a community college course I took that required me to open venv on VSCode. I'm not quite done with that course so I don't want to go about deleting files yet. However, I also don't want to sync everything to Github. Is there a straightforward to disable this syncing?_

**Comment by JnyJny** [comment]
There *is* a straightforward way of disabling this behavior (given the number of files it's probably trying to sync a virtual environment directory).

First, create a file named `.gitignore` in the top level folder of your git repository and add the name of the virtual environment folder. I don't know what the folder is named, but if it was named "venv" you would put this in your `.gitignore`:

```
venv/*
```

This says to ignore all entries found in the directory named venv.

After creating the file, git should find less things that it wants to sync to GitHub. You'll then add your `.gitignore` file to the repo and commit it.
