### ISSUE TITLE
Bite 15 - left Justify

### ISSUE THREAD

**Issue by vinostroud** [vinostroud/PDI_Bytes#2]
For Bite 15 my code appears to be running correctly, as this is my output (second column is left justified or appears so on the screen):

```
1. Julian     Australia  
2. Bob        Spain      
3. PyBites    Global     
4. Dante      Argentina  
5. Martin     USA        
6. Rodolfo    Mexico     
```

However it triggers this error:

```
apsys = <_pytest.capture.CaptureFixture object at 0x7f1aec588e50>

    def test_enumerate_names_countries(capsys):
        enumerate_names_countries()
        output = capsys.readouterr().out
>       assert output == expected_output
E       AssertionError: assert '' == '1. Julian   ...o    Mexico\n'
E         - 1. Julian     Australia
E         - 2. Bob        Spain
E         - 3. PyBites    Global
E         - 4. Dante      Argentina
E         - 5. Martin     USA
E         - 6. Rodolfo    Mexico

/tmp/test_enumerate_data.py:20: AssertionError
```

I'm assuming there's something off with my second column -- but I am not sure what.  Any tips you may have are appreciated!

**Comment by JnyJny** [comment]
Here is the code in question:
https://github.com/vinostroud/PDI_Bytes/blob/f4d1649d35fe0f47c43ce3a7c92d41726021a489/Bite%2015%20enumerate%20two%20strings_sequences.py#L6-L10

Learning how to read pytest output can be challenging, so lets break it down:

```console
    def test_enumerate_names_countries(capsys):
        enumerate_names_countries()
        output = capsys.readouterr().out
>       assert output == expected_output

```
This is the test code, and the `>` shows where the test failed. The assertion here is testing the output generated by your program to the expected output. Note here that the test is using a special pytest fixture called `capsys` which captures system output from functions like `print`.  This is our first clue about what might be going wrong.

Next is a description of the error that pytest found via the `assert` that fired in the test. The two things being compared were not equal, so the assert raised an AssertionError:

```console
E       AssertionError: assert '' == '1. Julian   ...o    Mexico\n'
E         - 1. Julian     Australia
E         - 2. Bob        Spain
E         - 3. PyBites    Global
E         - 4. Dante      Argentina
E         - 5. Martin     USA
E         - 6. Rodolfo    Mexico
```
Pytest replaces `output` and `expected_output` with the actual values in those variables. We can see that `output` is an empty string `''` while `expected_output` is composed of the list of name, country associations. 

This is our second clue and it's telling us that `capsys` is not seeing the expected output on the console.

With these clues I think you should be able to find what's missing and get the bite passing!

**Comment by vinostroud** [comment]
Alright, the return vs print error was especially silly give **print** is actually highlighted. Sorry. I do have one last issue on this one -- I'm stuck on the specifying margins/character sizing. If I understand the error, I am one character size off on the third column (Country), but I'm not sure how to fix it. I have been working on this and trying different combos for over an hour. What am I missing?

Code (but I've tried various combos, using left justify `<` : or simply sizing eg `:11`
```
names = 'Julian Bob PyBites Dante Martin Rodolfo'.split()
countries = 'Australia Spain Global Argentina USA Mexico'.split()


def enumerate_names_countries():
    results = ''
    for index, (name, country) in enumerate(zip(names, countries), 1):
        results += f'{index}. {name:<10} {country:<10}\n'
    print(results)

enumerate_names_countries()
```

Error:
```
capsys = <_pytest.capture.CaptureFixture object at 0x7f11b7dd1db0>

    def test_enumerate_names_countries(capsys):
        enumerate_names_countries()
        output = capsys.readouterr().out
>       assert output == expected_output
E       AssertionError: assert '1. Julian   ...exico    \n\n' == '1. Julian   ...o    Mexico\n'
E         - 1. Julian     Australia
E         + 1. Julian     Australia 
E         ?                        +
E         - 2. Bob        Spain
E         + 2. Bob        Spain     
E         ?                    +++++
E         - 3. PyBites    Global...
```

**Comment by JnyJny** [comment]
After all that talk, I tested my proposed solution an the pytest still fails! The final bug in your code is a case of over-specifying the formatting when creating each line the output. You have:
```python
        results += f"{index}. {name:<10} {country:<10}\n"
```

And I read over what pytest was telling us as I was focusing on the double newlines:

```console
>       assert output == expected_output
E       AssertionError: assert '1. Julian   ...exico    \n\n' == '1. Julian   ...o    Mexico\n'
E         - 1. Julian     Australia
E         + 1. Julian     Australia 
E         ?                        +
E         - 2. Bob        Spain
E         + 2. Bob        Spain     
E         ?                    +++++
E         - 3. PyBites    Global...
```

It's not easy to see at first, but the plus signs are indicating each characters in the output (which happen to be spaces and therefore much easier to miss). 

If we look at the tests expected output in a repl:
```python
>>> from textwrap import dedent
>>> expected_output = dedent(
...     """\
...     1. Julian     Australia
...     2. Bob        Spain
...     3. PyBites    Global
...     4. Dante      Argentina
...     5. Martin     USA
...     6. Rodolfo    Mexico
... """
... )
>>> expected_output
'1. Julian     Australia\n2. Bob        Spain\n3. PyBites    Global\n4. Dante      Argentina\n5. Martin     USA\n6. Rodolfo    Mexico\n'
```
We can see here that at the end of each line, there are no spaces between the end of each country name and the newline.

We can add a debugging line to your function to look at `results` in a similar fashion:

```python 
def enumerate_names_countries():
    results = ""
    for index, (name, country) in enumerate(zip(names, countries), 1):
        results += f"{index}. {name:<10} {country:<10}\n"

    print(repr(results))  # print the python representation of results
    #print(results)

>>> enumerate_names_countries()
'1. Julian     Australia \n2. Bob        Spain     \n3. PyBites    Global    \n4. Dante      Argentina \n5. Martin     USA       \n6. Rodolfo    Mexico    \n'
...
```
The `repr` builtin function isn't needed all the time, but in this case it helps us see the actual format of the string as if we had typed in the string.

Now it should be evident that there are spaces between the end of the country string and the newline which are missing in the expected output. The whitespace is coming from the format specifier for country, `{country:<10}`. 

In my opinion, this Bite is cruel since it can be very difficult to debug string comparisons with embedded white space.

**Comment by vinostroud** [comment]
OK, that was a tough one, this finally worked:
```
def enumerate_names_countries():
    results = ''
    for index, (name, country) in enumerate(zip(names, countries), 1):
        results += f'{index}. {name:<10} {country}\n'
    #print(repr(results))
    print(results, end="")
```
