### ISSUE TITLE
Bite 9, function within function

### ISSUE THREAD

**Issue by vinostroud** [vinostroud/PDI_Bytes#7]
In the last function below, `get_longest_palindrome` I couldn't figure out how to create an object using the second function,  `is_palindrome()`. The code below passes -- yay -- but this is obviously not the elegant way of solving the problem. No rush on this, we can look at it quickly tomorrow.

My code:
```
import os
import urllib.request

TMP = os.getenv("TMP", "/tmp")
DICTIONARY = os.path.join(TMP, 'dictionary_m_words.txt')
urllib.request.urlretrieve(
    'https://bites-data.s3.us-east-2.amazonaws.com/dictionary_m_words.txt',
    DICTIONARY
)


def load_dictionary():
    """Load dictionary (sample) and return as generator (done)"""
    with open(DICTIONARY) as f:
        return (word.lower().strip() for word in f.readlines())


def is_palindrome(word):
    sanitized_word = ''.join(char.lower() for char in word if char.isalnum())
    if sanitized_word == sanitized_word[::-1]:
        return word
    else:
        pass


def get_longest_palindrome(words=None):
    
    if words is None:
        words = list(load_dictionary())
        
    list_of_pals = []
    list_of_lengths = []
    
    for word in words: #question is here...how do I simply use the existing function is_palindrome rather than recreating it
        sanitized_word = ''.join(char.lower() for char in word if char.isalnum())
        if sanitized_word == sanitized_word[::-1]:
            list_of_pals.append(word)
    
    for palin in list_of_pals:
        #if len(i) > len(list_of_lengths[0]):
        list_of_lengths.append(len(palin))
    
    longest_palin = list_of_lengths.index(max(list_of_lengths))
    
    longest_pal_str = list_of_pals[longest_palin]

    return longest_pal_str
```

**Comment by JnyJny** [comment]
Ok the next part of the bite is taking a list of words, filtering the list to find the palindromes and then finding the longest word that is a palindrome. 

You wrote:
```
def get_longest_palindrome(words=None):
    
    if words is None:
        words = list(load_dictionary())
```
This is great and explicit about what you intend, if no words are given load words from the generator `load_dictionary`.  You chose to build a list from the generator right away by wrapping it in a `list()`.   So far so good.

```
    list_of_pals = []
    list_of_lengths = []
```
Things are going off the rails here. You've created two auxiliary lists, one for accumulating palindromes and one for tracking the lengths of those palindromes. It's not *wrong* but both of those things can be tracked by some judicious use of the innate attributes of lists and builtin python functions.

```
    for word in words: #question is here...how do I simply use the existing function is_palindrome rather than recreating it
        sanitized_word = ''.join(char.lower() for char in word if char.isalnum())
        if sanitized_word == sanitized_word[::-1]:
            list_of_pals.append(word)
```

Ok, your question here is how do I use `is_palindrome` here is a good one.

This code could be re-written like this:
```
    palindromes = [word for word in words if is_palindrome(word)]
```
This code is read as "The list palindromes is a list of words from the words list (or generator!) where is_palindrome(word) returns True".  

Functions we write are used just like the Python builtin functions, like `print` for instance. Functions are invoked with their name, an open parenthesis, any arguments the function requires in a comma separated list, followed by a close parenthesis. You can load your code into a Python repl to test this:


    
```
    for palin in list_of_pals:
        #if len(i) > len(list_of_lengths[0]):
        list_of_lengths.append(len(palin))
    
    longest_palin = list_of_lengths.index(max(list_of_lengths))
    
    longest_pal_str = list_of_pals[longest_palin]

    return longest_pal_str
```


I solved it this way:

```
def get_longest_palindrome(words=None):
    """Given a list of words return the longest palindrome
       If called without argument use the load_dictionary helper
       to populate the words list"""
    words = words or load_dictionary()
    return max((palindrome for palindrome in [word for word in words if is_palindrome(word)]), key=lambda v: len(v))
 ```
