### ISSUE TITLE
Bite 32 - no idea on the module

### ISSUE THREAD

**Issue by vinostroud** [vinostroud/PDI_Bytes#9]
Bite 32 asks me to take a global variable, `items`, create a local copy, mutate the local copy, return the local copy using the same name `items`, without mutating `global` `items`.

I could do this easily if I could return eg `local_items`, but after about an hour of searching around I am stuck. Is copy() the 

```
items = [{'id': 1, 'name': 'laptop', 'value': 1000},
         {'id': 2, 'name': 'chair', 'value': 300},
         {'id': 3, 'name': 'book', 'value': 20}]


def duplicate_items(items):
    return items[:]
```

mutation:

`
items_copy[0]['name'] = 'macbook'
items_copy[1]['id'] = 4
items_copy[2]['value'] = 30
`
It also seems like I should be able to do the mutation (`return items [mutation:mutations]` in one line, which also perplexes me.

Is there a resource you can point me to? Am I going at this backwards and should focus on changing the dictionary before worrying about creating `local` `items`?

**Comment by JnyJny** [comment]
The central concept of this bite is the idea that some copies don't act the way we might predict. In python there are two kinds of copies: a shallow copy and a deep copy.

Before we get to the differences between the two, we need to talk about the concept of equality versus identity.

Equality is an operation where we decide if two values are equal or not equal. For instance, using literal values:
```python
>>> 1 == 1
True
>>> 1 == 0
False
>>> 'A' == 'B'
False
```

Things get murkier when we start assigning values to variables and then trying to test their equality, especially when the values are containers (lists, dictionaries, sets and tuples). 

```python
>>> l = [ 1, 2, 3, 4]
>>> m = l
>>> l == m
True
>>> id(l) == id(m)
True
```
In this example, I've "made a copy" of `l` that is now called "m".  The two lists, `l` and `m` are equal but there's something else.  Remember, instances of classes are the "cookies the cookie cutter creates".  So each of the instances of a class are unique.  The `id` builtin function returns a number that uniquely identifies any instance of a class in Python.

But wait, the identities of `l` and `m` are the same?  This illustrates that there is one instance of the list in memory that is now associated with two "names", `l` and `m`.

```mermaid
flowchart
    l --> C
    m --> C[A List]
```

Ok great but what does this have to do with copying?

In python, the assignment operator performs a "shallow" copy where only the "id" is copied. So when we modify the "copied" value, it also changes the original value!

```python
>>> l = [1, 2, 3]
>>> m = l
>>> m[0] = "Surprise!"
>>> m
["Surprise!", 2, 3]
>>> l
["Surprise!", 2, 3]
```

The Bite wants you to perform a deep copy of `items` and return the copy. The tests ensure that the copy is a deep copy by mutating the copy and checking the original items to make sure they didn't change also. 

I was struggling a little with explaining shallow versus deep, so I asked ChatGPT and I think [the answer it gave][shallow-deep] was better and more focused then most articles I've read on the topic.  Give that a read and then take another shot at the Bite.

Another great question!

[shallow-deep]: https://chat.openai.com/share/e75606c1-8344-4429-af75-2736fc9a9482

**Comment by vinostroud** [comment]
OK, I think I've made the needed changes, but it still fails. I'm confused why.

Code: 
```
import copy

items = [{'id': 1, 'name': 'laptop', 'value': 1000},
         {'id': 2, 'name': 'chair', 'value': 300},
         {'id': 3, 'name': 'book', 'value': 20}]

def duplicate_items(items):
    items = copy.deepcopy(items)
    items[0]['name'] = 'macbook'
    items[1]['id'] = 4
    items[2]['value'] = 30
    return items[:]

print(duplicate_items(items))
print()
print(items)
```

This outputs as code:
```
[{'id': 1, 'name': 'macbook', 'value': 1000}, {'id': 4, 'name': 'chair', 'value': 300}, {'id': 3, 'name': 'book', 'value': 30}]

[{'id': 1, 'name': 'laptop', 'value': 1000}, {'id': 2, 'name': 'chair', 'value': 300}, {'id': 3, 'name': 'book', 'value': 20}]
```

I think this is expected?


Error is as follows. The function is pre-written to `return items[:]`, so I assumed that the `deepcopy()`variable in the function should have the same name: `items`. I realize in normal circumstances you would want different names for the `deepcopy()` variable in the function. So I suspect I am missing some detail in the expected output.

```

============================= test session starts ==============================
platform linux -- Python 3.10.11, pytest-7.0.1, pluggy-0.13.1
rootdir: /tmp
plugins: anyio-3.5.0, asyncio-0.18.2, cov-2.12.0
asyncio: mode=strict
[{'id': 1, 'name': 'macbook', 'value': 1000}, {'id': 4, 'name': 'chair', 'value': 300}, {'id': 3, 'name': 'book', 'value': 30}]

[{'id': 1, 'name': 'laptop', 'value': 1000}, {'id': 2, 'name': 'chair', 'value': 300}, {'id': 3, 'name': 'book', 'value': 20}]
collected 1 item

../../tmp/test_inventory.py F

=================================== FAILURES ===================================
____________________________ test_change_copy_only _____________________________

    def test_change_copy_only():
        items_copy = duplicate_items(items)
>       assert items == items_copy
E       AssertionError: assert [{'id': 1, 'n... 'value': 20}] == [{'id': 1, 'n... 'value': 30}]
E         At index 0 diff: {'id': 1, 'name': 'laptop', 'value': 1000} != {'id': 1, 'name': 'macbook', 'value': 1000}
E         Use -v to get the full diff

/tmp/test_inventory.py:6: AssertionError
=========================== short test summary info ============================
FAILED ../../tmp/test_inventory.py::test_change_copy_only - AssertionError: a...
============================== 1 failed in 0.08s ===============================
```

**Comment by JnyJny** [comment]
You've slightly misunderstood the Bite description:

>In this Bite you are presented with a function that copies the given items data structure.
>There is a problem though, the tests fail. Can you fix it?
>This can be done in a one liner. If you know which module to use it will be easy, if not you will learn something new today.

Your function needs to copy the function's argument and return the copy and the tests will mutate the copy. Mutating the copy and checking the original is how the deep copy is verified (if it's a shallow copy, the original will be changed when the shallow copy is mutated).

**Comment by vinostroud** [comment]
indeed I did misunderstand the intent -- thank you for the clarification, closing!
